export const COMMAND_ID = Object.freeze({
    STATE: 0x03,
    DEVICE_INFO: 0x04,
    FACTORY_RESET: 0x06,

    BACKUP_POWER_CONTROL: 0x0F,
    DISCHARGE_POWER_LIMIT_CONTROL: 0x15,

    SURPLUS_FEED_IN_CONTROL: 0x41,
    BATTERY_MODULES_STATE: 0x42,

    DEPTH_OF_DISCHARGE_CONTROL: 0x54,

    LED_CONTROL: 0x59
})

export type COMMAND_ID = (typeof COMMAND_ID)[keyof typeof COMMAND_ID];
